Marketo.UI/Areas/Admin/Controllers/AboutController.cs
using FianlProject.Extensions;
using Marketo.Core.Entities;
using Marketo.DataAccess.Contexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Marketo.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, Moderator")]

    public class AboutController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public AboutController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<About> abouts = _context.Abouts.ToList();
            _context.SaveChanges();
            return View(abouts);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0) return NotFound();
            About about = await _context.Abouts.FirstOrDefaultAsync(s => s.Id == id);
            if (about == null) return NotFound();
            return View(about);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(int? id, About about)
        {
            if (id == null || id == 0) return NotFound();
            About existed = await _context.Abouts.FindAsync(id);
            if (existed == null) return NotFound();
            if (about.Photo == null)
            {
                string filename = existed.Image;
                _context.Entry(existed).CurrentValues.SetValues(about);
                existed.Image = filename;
            }
            else
            {
                if (!about.Photo.ImageIsOkey(3))
                {
                    ModelState.AddModelError("Photo", "choose image file");
                    return View(existed);
                }
                FileExtension.FileDelete(_env.WebRootPath, "assets/image", existed.Image);
                _context.Entry(existed).CurrentValues.SetValues(about);
                existed.Image = await about.Photo.FileCreate(_env.WebRootPath, "assets/image");
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
    }
}

Marketo.UI/Areas/Admin/Views/About/Index.cshtml
@model List<About>
@{
    ViewData["Title"] = "Index";
}

<div class="main-panel">
    <h5 class="d-flex" style="justify-content: center; background-color: #d1e7dd; color: #000; font-size: 20px; padding: 10px;">About</h5>
    <div class="table-responsive">
        <table class="table table-bordered" style="text-align: center; padding-top: 0px !important;">
            <thead class="table table-success" style="text-align: center">
                <tr>
                    <th>
                        Image
                    </th>
                    <th>
                        SubTitle
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Desc
                    </th>
                    <th>
                        Order
                    </th>
                    <th>
                        Edit
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (About about in Model)
                {
                    <tr class="table-light">
                        <td>
                            <img style="width:110px; height:110px"
                             src="~/assets/image/@about.Image" />
                        </td>
                        <td>
                            @about.SubTitle
                        </td>
                        <td>
                            @about.Title
                        </td>
                        <td>
                            @about.Desc
                        </td>
                        <td>
                            @about.Order
                        </td>
                        <td class="d-flex align-items-center" style="height:160px; justify-content: center; gap: 5px">
                            <div>
                                <a asp-area="Admin" asp-controller="About" asp-action="Edit" asp-route-id="@about.Id"
                               class="btn btn-outline-success"><i class="mdi mdi-border-color"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Marketo.UI/Areas/Admin/Views/About/edit.cshtml
@model About
@{
    ViewData["Title"] = "Edit";
}

<main class="main-panel">
    <h1 style="text-align:center; background-color:chartreuse">Edit About</h1>
    @if (TempData["Filname"] != null)
    {
        <div class="alert alert-danger">@TempData["Filename"]</div>
    }
    <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>
    <form method="post" class="mt-2" enctype="multipart/form-data">
        <div>
            <label>Images:</label><br />
            <input asp-for="Photo" class="form-control" /><br />
            <span classs="text-danger" asp-validation-for="Photo"></span>
        </div>
        <div>
            <label>SubTitle:</label><br />
            <input asp-for="SubTitle" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="SubTitle"></span>
        </div>
        <div>
            <label>Title:</label><br />
            <input asp-for="Title" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Title"></span>
        </div>
        <div>
            <label>Desc:</label><br />
            <input asp-for="Desc" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Desc"></span>
        </div>
        <div>
            <label>Order:</label><br />
            <input asp-for="Order" type="text" class="form-control" /><br />
            <span class="text-danger" asp-validation-for="Order"></span>
        </div>
        <div class="mt-5">
            <button class="btn btn-success" type="submit"> Update </button>
        </div>
    </form>
</main>