Marketo.UI/Areas/Admin/Controllers/SellerController.cs
using Marketo.Core.Entities;
using Marketo.DataAccess.Contexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Marketo.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
[Authorize(Roles = "Admin, Moderator")]

    public class SellerController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public SellerController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            int max = 8;
            double pageCountsort = Math.Ceiling((double)((decimal)_context.Furnitures.Count() / Convert.ToDecimal(max)));
            List<Furniture> model = await _context.Furnitures.Include(c => c.Categories).Include(c => c.Furnitureimages).ToListAsync();
            ViewBag.CurentPage = page;
            ViewBag.TotalPage = pageCountsort;
            return View(model);
        }
        public async Task<IActionResult> Trend(int id)
        {
            Furniture furniture = _context.Furnitures.FirstOrDefault(m => m.Id == id);
            if (furniture.Trend == false)
            {
                furniture.Trend = true;
            }
            else if (furniture.Trend == true)
            {
                furniture.Trend = false;
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

Marketo.UI/Areas/Admin/Views/Seller/Index.cshtml
@model List<Furniture>
@{
    ViewData["Title"] = "Index";
}

    @{
        if (TempData["FileName"] != null)
        {
    <div class="alert alert-danger">@TempData["FileName"]</div>
        }
    }

    <div style="width:83%;" class="table-responsive ">
    <h5 class="d-flex" style="justify-content: center; background-color: #d1e7dd; color: #000; font-size: 20px; padding: 10px;">General Seller</h5>
    <table id="myDataTable" class="table table-bordered" style="text-align: center">
            <thead class="table table-info" style="text-align: center">
                <tr>
                    <th>
                        Image
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        SKU
                    </th>
                    <th>
                        Article
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        isTrend
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Furniture furniture in Model)
                {
                    <tr class="table-light">
                        <td>
                            <img style="width:110px; height:110px"
                             src="~/assets/image/shop/@furniture.Image" />
                        </td>
                        <td>
                            @furniture.Name
                        </td>
                        <td>
                            @furniture.SKU
                        </td>
                        <td>
                            @furniture.Article.Substring(0,70)
                            .....
                        </td>
                        <td>
                            @furniture.Price
                        </td>
                        <td class="d-flex align-items-center" style="height:160px; justify-content: center; gap: 5px">
                        @if (furniture.Trend==true)
                        {
                            <div>
                                <a asp-area="Admin" asp-controller="Seller" asp-action="Trend" asp-route-id="@furniture.Id"
                                class="btn btn-outline-success"><i class="mdi mdi-heart"></i></a>
                            </div>
                        }
                        else{
                            <div>
                                <a asp-area="Admin" asp-controller="Seller" asp-action="Trend" asp-route-id="@furniture.Id"
                                class="btn btn-danger"><i class="mdi mdi-heart-broken"></i></a>
                            </div>
                        }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
     
    </div>
</div>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://code.jquery.com/jquery-3.6.4.js"
        integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#myDataTable').DataTable();
    });
</script>